openapi: 3.0.1
info:
  title: Pomodoro Notes OpenAPI Resource Document
  version: "1.0"

servers:
  - url: http://localhost:8080/
    description: Optional dev mode server description
  - url: http://localhost:28080/
    description: Optional dev mode container server description

paths:
  /tasks:
    get:
      responses:
        200:
          description: OK - task list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        200:
          description: new minitask resource created
          content:
            application/json: {}
  /tags:
    get:
      responses:
        200:
          description: OK - tag list
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
components:
  schemas:
    Task:
      properties:
        id:
          type: string
        content:
          type: string
        tags:
          type: array
          items:
            type: string
        recordedAt:
          type: string
